services:
  timescale:
    container_name: timescale3
    image: timescale/timescaledb:latest-pg12
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - POSTGRES_PASSWORD=1
    ports:
      - 5432:5432
    restart: always
  apps:
    container_name: app
    image: my-golang-app:latest
    ports:
      - 8081:8080
    restart: always